### PR TITLE
changes based on the results of the blog-header-logo test (using a lo…

### PR DESCRIPTION
**Pull request by thtmnisamnstr**
…go w/ the tagline 'Super Simple Builds'

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://648223c654aa8330a2e7fa84--ephemeral-narwhal-3ac3b2.netlify.app/blog

**Comment by thtmnisamnstr** [comment]
@vladaionescu @adamgordonbell When you get a chance, could one of you approve this PR? It's committing the results of the A/B test for header logos on the blog. The logo w/ the tagline "Super Simple Builds" won.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6482371db023d2036540e89c--ephemeral-narwhal-3ac3b2.netlify.app/blog

**Review by vladaionescu — APPROVED** [review]
Yay!

**Pull request merged**
