### PR TITLE
Blog - A biased take on the ROI of fast

### PR DESCRIPTION
**Pull request by msali123**
Done with all checks.

### CODE REVIEW

**Comment by msali123** [comment]
@adamgordonbell  [Preview Link](https://653104a6a705cc108faf5ae7--ephemeral-narwhal-3ac3b2.netlify.app/blog/the-roi-of-fast/)

**Comment by vladaionescu** [comment]
This image from the other article would work well for the "try your own" section.

Screenshot 2023-10-19 at 10 56 13 AM

Remember to also fix the link in the first paragraph to point back to the article in the other PR.

**Comment by msali123** [comment]
[Updated link](https://65318838f814111ffc6a51f2--ephemeral-narwhal-3ac3b2.netlify.app/blog/the-roi-of-fast/) @vladaionescu

**Comment by vladaionescu** [comment]
This looks good!

**Review by vladaionescu — APPROVED** [review]

**Comment by vladaionescu** [comment]
We should wait for the other PR (https://github.com/earthly/website/pull/694) to merge at the same time.

**Pull request merged**
