### PR TITLE
Solutions page

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by avinder-red-crackle** [comment]
Preview URL: https://64f58000d2209b0dd8574f72--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
This looks great. I'm going to update some copy, hide a few sections we'll need in the future, and merge this today.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64f8f4e3e7584d28ce607471--ephemeral-narwhal-3ac3b2.netlify.app/solutions

**Comment by thtmnisamnstr** [comment]
One last thing. Can we change the icon above "Ridiculously fast" in the hero? Something that connotates fast, like a speedometer.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64f9d62df6c3202022a53b82--ephemeral-narwhal-3ac3b2.netlify.app/solutions

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64fa129e1e391134caf1fa79--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64fa170c3215bb3759cbc79c--ephemeral-narwhal-3ac3b2.netlify.app

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
