### PR TITLE
Github Actions runner in pro tier

### PR DESCRIPTION
**Pull request by idelvall**
Removes redundancy in the tiers and adds Github Actions runner support in the pro tier.

Context:
- https://github.com/earthly/earthly/pull/4140/
- https://docs.google.com/document/d/1bk0-3SNdBc7OJCkNo82XNz1UR_SwQcvw5-yRQcTCq8U/edit

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://664efd1948fb0fca1a69fa5c--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Review by vladaionescu — APPROVED** [review]
This looks good to me!

CC @thtmnisamnstr for a review too.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://664f840f97fbc23f756b0cd4--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Review by thtmnisamnstr — APPROVED** [review]

**Comment by thtmnisamnstr** [comment]
lgtm

**Comment by idelvall** [comment]
Added links:
https://664f8c49ed86744ba4c3ce73--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Pull request merged**
