### PR TITLE
Blog - Mastering the Art of Logging in Python: A Complete Guide

### PR DESCRIPTION
**Pull request by msali123**
Done with all checks.

### CODE REVIEW

**Comment by msali123** [comment]
[Preview Link](https://642f5d448fe71f2eb898eace--ephemeral-narwhal-3ac3b2.netlify.app/blog/logging-in-python/)

@balapriyac

**Review by balapriyac — CHANGES_REQUESTED** [review]
Thanks, Sameer. Just added a couple minor suggestions.

**Comment by msali123** [comment]
@balapriyac 

[Changes done](https://642fee9051ee2f1eb2259e0f--ephemeral-narwhal-3ac3b2.netlify.app/blog/logging-in-python/)

**Comment by balapriyac** [comment]
@jalletto this is ready to merge.

**Review by jalletto — APPROVED** [review]

**Pull request merged**
