### PR TITLE
Blog header CTA update

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://646cf537d371e52179e5557e--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle In the mobile menu, it looks like "Learn Earthly" isn't centered in the button. Can you center the text in the button?
image

**Comment by avinder-red-crackle** [comment]
@thtmnisamnstr This is fixed.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://646de0541873d279658d13ea--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://646e8012ad16222ad4c6b5b1--ephemeral-narwhal-3ac3b2.netlify.app

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
