### PR TITLE
updated website metatags and social card

### PR DESCRIPTION
**Pull request by thtmnisamnstr**

### CODE REVIEW

**Review by vladaionescu — COMMENTED** [review]
In the image twitter-card-large - I wonder if we should remove the first sentence as it's a repeat of the large text anyway?

**Comment by thtmnisamnstr** [comment]
You're right. I'll update the card tomorrow.

**Comment by thtmnisamnstr** [comment]
@vladaionescu I updated the social card.

**Review by vladaionescu — APPROVED** [review]

**Comment by vladaionescu** [comment]
Looks great!

**Pull request merged**
