### PR TITLE
Clearer speed argument

### PR DESCRIPTION
**Pull request by vladaionescu**
Based on some user feedback

### CODE REVIEW

**Comment by vladaionescu** [comment]
Preview URL: https://64b19a82ebeaab00836e6c42--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by vladaionescu** [comment]
Preview URL: https://64b43c568ca8dd653732a90a--ephemeral-narwhal-3ac3b2.netlify.app/

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b580e047333e3b78a5b06b--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b58344b3b852385c22ebad--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b585c3b3b8523a0822eb58--ephemeral-narwhal-3ac3b2.netlify.app

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
