### PR TITLE
Blog - Updates and Enhancements to the Earthly Cloud UI

### PR DESCRIPTION
**Pull request by msali123**
Done with all checks.

### CODE REVIEW

**Comment by msali123** [comment]
@thtmnisamnstr [Preview Link](https://665a0567cf1d346e80a73f67--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-cloud-ui-updates/)

**Comment by thtmnisamnstr** [comment]
This looks good. There are some changes I'd like to make after seeing it laid out. I'll make those on Monday and merge it then.

**Comment by msali123** [comment]
Okay sure, let me know if I can do them.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://665e0b94c5fcfd41f3f7122d--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-cloud-ui-updates/

**Comment by thtmnisamnstr** [comment]
Preview URL: https://665e120aa3d21d4ab87c65e6--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-cloud-ui-updates/

**Pull request merged**
