### PR TITLE
Blog - What makes Earthly fast

### PR DESCRIPTION
**Pull request by msali123**
Done with all checks.

### CODE REVIEW

**Comment by msali123** [comment]
@adamgordonbell [Preview Link](https://6530df6edf3ee60bf905b15b--ephemeral-narwhal-3ac3b2.netlify.app/blog/what-makes-earthly-fast/)

**Comment by vladaionescu** [comment]
Can we change the "how" image to something a little more representative? Like some machinery / factory / gears?

Also we should change or remove the star image, just in case it has some political connotation.

Please also fix the link under "the ROI of fast" to point to the article in the other PR.

**Comment by msali123** [comment]
[UPDATED LINK](https://6531909754b4902052a736d9--ephemeral-narwhal-3ac3b2.netlify.app/blog/what-makes-earthly-fast/) @vladaionescu

**Comment by vladaionescu** [comment]
Thanks!

The statue of liberty image doesn't really fit well either. Let's just remove that image altogether.

I just noticed that the wording in the header image can be improved

Screenshot 2023-10-19 at 1 31 43 PM

It might be better to just use the title of the article "What makes Earthly fast". If you add the Earthly logo in that sentence, can you put it in front of the word Earthly, instead of after it?

**Comment by msali123** [comment]
header
Is it okay to go?

**Comment by vladaionescu** [comment]
👍

**Comment by vladaionescu** [comment]
Please merge at the same time with https://github.com/earthly/website/pull/695

**Review by vladaionescu — APPROVED** [review]

**Comment by msali123** [comment]
[Preview Link](https://653199c3152974008b856252--ephemeral-narwhal-3ac3b2.netlify.app/blog/what-makes-earthly-fast/)

**Pull request merged**
