### PR TITLE
Update homepage

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle leave the customer quotes section unchanged for now. We need design from Miron before we can do that part. Everything else should be ok to do now.

**Comment by avinder-red-crackle** [comment]
Preview URL: https://64782b3f2754a83b75e490bd--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6478db2af0c1503880bd06fc--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6478dea19aa2cf34daaa073f--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
For the Adopt Incrementally section, could you make the graphic above the text on mobile?
image

**Comment by thtmnisamnstr** [comment]
Preview URL: https://647d6941c08dfa24ef8bc92f--ephemeral-narwhal-3ac3b2.netlify.app

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
