### PR TITLE
add earthly satellite ga blog

### PR DESCRIPTION
**Pull request by jalletto**

### CODE REVIEW

**Comment by jalletto** [comment]
Preview: https://645ae07fc3f3815025a4a042--ephemeral-narwhal-3ac3b2.netlify.app/blog/earthly-satellites-ga/

**Comment by vladaionescu** [comment]
The banner image is blurry. I have noticed that this is something common with our banner images in other blog posts - is there something we can do to monitor the quality of our images and diagrams more closely?

See the sharpness difference between the text in the banner vs the GitHub star counter.

Screenshot 2023-05-09 at 5 20 54 PM

Blurry images make a bad impression on the quality of our blog.

**Comment by vladaionescu** [comment]
Another example:

Screenshot 2023-05-09 at 5 24 03 PM

**Comment by adamgordonbell** [comment]
> Another example:
> 
> Screenshot 2023-05-09 at 5 24 03 PM

Interesting observation. The headers use source sets with webp as recommended by the lighthouse score, but even the largest looks fuzzy:
https://645ae07fc3f3815025a4a042--ephemeral-narwhal-3ac3b2.netlify.app//blog/generated/assets/images/earthly-satellites-ga/header-1200-60d890436.webp

And the source image does not:
https://github.com/earthly/website/blob/af6ebda7e628b1142ad4c30ea8c509145f8afab7/blog/assets/images/earthly-satellites-ga/header.jpg

That seems to imply we can change some compression settings and get better but larger images.

**Comment by vladaionescu** [comment]
Indeed - I wonder if the compression algorithm is fooled by the .jpg extension. The original images seem to be png in reality.

**Comment by vladaionescu** [comment]
Oh I'm noticing that the resolution goes from 4000x1000 to 1200x300. This would explain the significant drop in sharpness. Maybe we need to update the widths [here](https://github.com/earthly/website/blob/main/blog/_data/picture.yml#L43)?

**Comment by vladaionescu** [comment]
Reading around the web on this topic, it seems that the recommendation for retina displays is to produce images with double the pixels. Since the maximum width seems to be 1260, I think we just need to add a 2520-wide variant.

**Comment by adamgordonbell** [comment]
> Reading around the web on this topic, it seems that the recommendation for retina displays is to produce images with double the pixels. Since the maximum width seems to be 1260, I think we just need to add a 2520-wide variant.

Yep, I'll look at it in another PR.

**Review by thtmnisamnstr — APPROVED** [review]

**Comment by thtmnisamnstr** [comment]
Preview URL: https://645c05b45aa46400a8755bab--ephemeral-narwhal-3ac3b2.netlify.app/

**Pull request merged**
