### PR TITLE
Webinars

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by avinder-red-crackle** [comment]
Preview URL: https://64edd5a5eb6a5509c76f348c--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
In the Discover More section, can we automatically pull from our Youtube channel, https://www.youtube.com/@EarthlyTech, sorted by date descending?

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64fb23c8df92e6072cdc67a8--ephemeral-narwhal-3ac3b2.netlify.app/webinars

**Comment by thtmnisamnstr** [comment]
Can we change the page slug to /videos and the page name to Videos and Webinars?

**Comment by adamgordonbell** [comment]
For the featured carousel, can we have these:

- https://www.youtube.com/watch?v=m9dhrq9iRHA
- https://youtu.be/yJek26lyXZ0
- https://youtu.be/JOsWB50LmwQ

And for the section under that:
- https://www.youtube.com/watch?v=tAQx2oYU-vw
- https://www.youtube.com/watch?v=WJE4NHI7dPg
- https://www.youtube.com/watch?v=Z8ShM-SFxzM

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64ff8288db4b095964a18681--ephemeral-narwhal-3ac3b2.netlify.app/videos

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64ffebbdfa00dc1d65fbc0d9--ephemeral-narwhal-3ac3b2.netlify.app/videos

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle This is strange. The most recent preview (https://64ffebbdfa00dc1d65fbc0d9--ephemeral-narwhal-3ac3b2.netlify.app/videos) doesn't have any videos pulled from YouTube. The `_data/webinar-videos.json` file is up-to-date, but the YouTube API call fails in CI due to authentication issues (not a surprise).

Any idea what's going on? Is there a possibility the failed API call is overwriting the `_data/webinar-videos.json` file as empty? If so, can we handle a failed YT API call so that it doesn't overwrite the file?

**Comment by thtmnisamnstr** [comment]
@adamgordonbell Where in the navigation should the Videos & Webinars page live?

In the footer, it should be under the Content section, after Newsletter.

Do you think it should be in the header too? If so where (should we change the Blog header navigation item to a drop-down like the Products header navigation item?)

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6501a73fcb503c7d7ee771a8--ephemeral-narwhal-3ac3b2.netlify.app/videos

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6501f74f6632e62af60bcde3--ephemeral-narwhal-3ac3b2.netlify.app/videos

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
