### PR TITLE
Change Nobody Likes ... section to drawer-style expansions on mobile

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6452403dc248186f0768db0c--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
@mirho @vladaionescu Thoughts on this change? You'll only see the changes on mobile. I think it looks pretty good, but I defer to Miron.

**Review by vladaionescu — APPROVED** [review]
Looks great - deferring the design review to @mirho.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6453f84b74b11329de71fe37--ephemeral-narwhal-3ac3b2.netlify.app

**Review by mirho — APPROVED** [review]

**Pull request merged**
