### PR TITLE
updated standard bottom CTAs in blog posts

### PR DESCRIPTION
**Pull request by thtmnisamnstr**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65666656022a81008cdd434e--ephemeral-narwhal-3ac3b2.netlify.app/blog/

**Comment by vladaionescu** [comment]
Gavin also suggested this offline:

---

Earthly Cloud: Consistent, Fast Builds, Any CI
Consistent, repeatable builds across all environments. Advanced caching for faster builds. Easy integration with any CI. 6,000 build minutes per month included.
Get Started Free

**Review by adamgordonbell — APPROVED** [review]

**Comment by adamgordonbell** [comment]
LGTM. 
If we want to test out the specific wording, there is lots of traffic to do A/B testing.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6567794ad07b794408985c6d--ephemeral-narwhal-3ac3b2.netlify.app/blog/

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65677ea9e50eab4aee9a02ba--ephemeral-narwhal-3ac3b2.netlify.app/blog/

**Pull request merged**
