### PR TITLE
added anchor links to the Pricing page

### PR DESCRIPTION
**Pull request by thtmnisamnstr**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Added 3 anchors to the pricing page:
- #cloud-pricing
- #compute-pricing
- #faq

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6580ca51738f652e5c80fa4a--ephemeral-narwhal-3ac3b2.netlify.app/pricing (anchor example: https://6580ca51738f652e5c80fa4a--ephemeral-narwhal-3ac3b2.netlify.app/pricing#faq)

**Comment by vladaionescu** [comment]
The anchor symbol (¶) doesn't look great - the spacing / positioning is odd. Could we remove it or make it show on title hover only?

**Comment by thtmnisamnstr** [comment]
Removing is easy. On hover is easy. On title hover is difficult.

I'd like to remove the anchor symbol. The only problem with removing is that we have to remember that the anchor is there, remember what the anchor link is to use it, and it becomes only useful to us.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6580d2f3ff0bc22f8daaed43--ephemeral-narwhal-3ac3b2.netlify.app/pricing

Anchor symbol has been removed. Use:

- https://6580d2f3ff0bc22f8daaed43--ephemeral-narwhal-3ac3b2.netlify.app/pricing#cloud-pricing
- https://6580d2f3ff0bc22f8daaed43--ephemeral-narwhal-3ac3b2.netlify.app/pricing#compute-pricing
- https://6580d2f3ff0bc22f8daaed43--ephemeral-narwhal-3ac3b2.netlify.app/pricing#faq

**Review by vladaionescu — APPROVED** [review]
That works!

**Comment by thtmnisamnstr** [comment]
@vladaionescu I like it best w/ no anchor symbols at all. The anchor links still work, you just have to know that they are `#cloud-pricing`, `#compute-pricing`, and `#faq`.

**Pull request merged**
