### PR TITLE
Blog - Container Image Build Tools_ Docker vs. Buildah vs. kaniko

### PR DESCRIPTION
**Pull request by msali123**
Done with all checks.

### CODE REVIEW

**Comment by jalletto** [comment]
@msali123 Looks like this failed to build do a linting issue.

**Comment by msali123** [comment]
@jalletto please review

**Comment by adamgordonbell** [comment]
Otherwise, it looks good.

**Comment by msali123** [comment]
Yes I don't have the access to resolve the issue.
I've added a word for Lint warnings, I don't know why it says conflict

**Comment by jalletto** [comment]
@msali123 you might need to pull the current main branch in and resolve the conflicts locally if you don't have access to the resolve button. Let me know if you need a hand.

**Comment by msali123** [comment]
@jalletto I need your help brother

**Pull request merged**
