### PR TITLE
Earthly for Rust

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65819220f97bef06f576954f--ephemeral-narwhal-3ac3b2.netlify.app/rust

**Comment by avinder-red-crackle** [comment]
We are displaying published date in featured content section, but for the doc, we don't have any date. What should we display in this case?

**Comment by thtmnisamnstr** [comment]
Preview URL: https://658204ef646ba265b6050f3b--ephemeral-narwhal-3ac3b2.netlify.app/rust & https://658204ef646ba265b6050f3b--ephemeral-narwhal-3ac3b2.netlify.app/solutions

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle I made some updates (one addressing the published date question you asked). I don't like the graphic for Rust used on https://658204ef646ba265b6050f3b--ephemeral-narwhal-3ac3b2.netlify.app/solutions. Can we change it? Maybe just a grayscale Rust logo?

**Comment by avinder-red-crackle** [comment]
Preview URL: https://658299fea756fa006edc57bd--ephemeral-narwhal-3ac3b2.netlify.app/solutions

**Comment by thtmnisamnstr** [comment]
I like it. I'm going to merge these changes.

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
