### PR TITLE
Download Earthly in footer nav

### PR DESCRIPTION
**Pull request by thtmnisamnstr**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b716c82bbf0a15f0c218e7--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b71ae81889d620f4ecd36d--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b71ff2af2fd3239c9d2194--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
@vladaionescu I'd like your review on this. It's the footer changes (both website and blog) to add "Download Earthly" (and Earthly Cloud).

**Review by vladaionescu — COMMENTED** [review]
I like the intention, although the staggering doesn't look right. It looks disorganized at first glance. Maybe bullets can help clean things up? I'm not sure. Or failing that, just not staggering at all?

BTW, can you also add something at the top of the /get-earthly page to say that Earthly works best when you're logged in? Just so we encourage people toward the main flow.

**Comment by thtmnisamnstr** [comment]
I have two options for this.

**Option 1 - w/o bottom borders**
Desktop
image

Mobile
image

**Option 2 - w/ bottom borders**
Desktop
image

Mobile
image

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b840ac1522e21d9423a661--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by vladaionescu** [comment]
Bottom borders could work. I wonder if the download link should just go under Resources, to keep Products about the presentation of those products only. If we just call it "Downloads" instead of "Download Earthly", then it would fit on a single line on mobile, I believe. Maybe then we wouldn't need the bottom borders.

**Comment by thtmnisamnstr** [comment]
We kinda need the bottom borders anyway. Earthly Satellites and Earthly + GitHub Actions both are multiple lines too.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b86afbf63d9816b512c07c--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
What do you think about Download being bold, https://64b86afbf63d9816b512c07c--ephemeral-narwhal-3ac3b2.netlify.app/?

**Comment by vladaionescu** [comment]
> We kinda need the bottom borders anyway. Earthly Satellites and Earthly + GitHub Actions both are multiple lines too.

Ok fair enough.

> What do you think about Download being bold

Bold for download if fine with me

**Review by vladaionescu — APPROVED** [review]

**Pull request merged**
