### PR TITLE
Quotes redesigned

### PR DESCRIPTION
**Pull request by avinder-red-crackle**
@thtmnisamnstr I need image for **Ses Goe** from NOCD and mobile view designs.

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Desktop
image

Mobile (not final designs)
image

**Comment by thtmnisamnstr** [comment]
@vladaionescu Any feedback on the homepage quote redesign (ignore mobile, we're waiting on designs for it)?

**Comment by vladaionescu** [comment]
I was thinking this would be significantly smaller - it takes a lot of real estate from the screen. Is there a preview link I can look at?

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6488e280304b6923c407e96e--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64c293748976790cf16c3ff0--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64c297633cd8b60fd2eeb204--ephemeral-narwhal-3ac3b2.netlify.app

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
