### PR TITLE
add the new header, and footer to the blog

### PR DESCRIPTION
**Pull request by mirho**
- Adds the new header, and footer of the website to the blog
- updated the _config.yml so inline SVGs would work

See preview below:

image

image

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
@mirho This looks really good, but readers should have some way to navigate to Blog Home and, preferably, the categories Articles, News, and Tutorials. Basically we need the selections in the existing blog header somewhere. At a minimum, Blog Home

**Comment by mirho** [comment]
@thtmnisamnstr the blog home is already in the header actually. Blog 

image

**Comment by thtmnisamnstr** [comment]
I completely spaced that. I'm good with this then. Add me as a reviewer, and I'll approve. Adam's out today.

**Comment by mirho** [comment]
Looks like the production build is not generating an updated tailwind, will investigate

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
