### PR TITLE
Blog - AWS Graviton

### PR DESCRIPTION
**Pull request by msali123**
Done with all required checks.

### CODE REVIEW

**Comment by msali123** [comment]
@jalletto @vladaionescu  Review Required

**Comment by jalletto** [comment]
@msali123 I'm looking this over now. Just a quick note, Github randomly assigns members of our Org as reviewers, but Adam and I are the main owners of this repo so you can tag one of us for questions instead of Vlad.

**Comment by msali123** [comment]
> 

Yes sorry that was by mistake😬

**Comment by jalletto** [comment]
No worries :)

**Pull request merged**
