### PR TITLE
Monorepo Builds

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by avinder-red-crackle** [comment]
Preview URL: https://6557825822ce8c39da06cc4a--ephemeral-narwhal-3ac3b2.netlify.app/monorepos

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6557ac3d572ab30526c7fe1c--ephemeral-narwhal-3ac3b2.netlify.app/monorepos

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6557b8dafbb0930e817cfd55--ephemeral-narwhal-3ac3b2.netlify.app/monorepos

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6557e431572ab32d2cc7fde2--ephemeral-narwhal-3ac3b2.netlify.app/monorepos

**Comment by avinder-red-crackle** [comment]
Preview URL: https://655ae2c193efb13b73fda496--ephemeral-narwhal-3ac3b2.netlify.app/monorepos

**Comment by thtmnisamnstr** [comment]
Preview URL: https://655bd6526bf0683570a6074b--ephemeral-narwhal-3ac3b2.netlify.app/monorepos

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
