### PR TITLE
Blog - AWS S3 Backup and Recovery With Restic

### PR DESCRIPTION
**Pull request by msali123**
Done with all checks.

### CODE REVIEW

**Comment by msali123** [comment]
Preview URL:
https://63fc8c85ee4da915da1a177f--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by msali123** [comment]
@jalletto @balapriyac let me know if need to remove image captions

**Comment by balapriyac** [comment]
@msali123 

Hi Sameer,

Here's a quick note on image captions:

- Images that are there _only_ to introduce breaks (the ones you create on canva) need not be captioned.
- Images that are part of the discussion, like screenshots of outputs and steps, architecture diagrams, etc. should be captioned.

Please let me know if that helps.

**Comment by msali123** [comment]
Perfect @balapriyac this is okay to review then.

**Review by jalletto — APPROVED** [review]

**Pull request merged**
