### PR TITLE
Change Nobody Likes ... section to be the 4 points in the launch blog

### PR DESCRIPTION
**Pull request by avinder-red-crackle**
1. Updated the content as per doc.
2. Added bullet points
3. Change selected point on hover instead of on click

### CODE REVIEW

**Comment by mirho** [comment]
@thtmnisamnstr looks good. A few points:

1) The containing box should have a consistent height so that it does not change when you hover over different elements. I noticed that the content below shifted up on hover because the beige box is not a fixed size.
2) Would add some more padding between the bullet points to make them easier to read

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64522c8ccbe4975649b4a2fa--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
I think this looks good now. @mirho @vladaionescu any changes you want before we merge?

**Review by vladaionescu — APPROVED** [review]
Looks good to me!

This still doesn't work on mobile, but perhaps that can be a separate change.

**Review by mirho — APPROVED** [review]

**Comment by mirho** [comment]
@thtmnisamnstr looks good 👍

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6453e036b49908167bd59f15--ephemeral-narwhal-3ac3b2.netlify.app

**Pull request merged**
