### PR TITLE
Pricing page updates

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65c9f57c8e8612c9bb6cdf09--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65ca47da50bbe812586317a9--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by thtmnisamnstr** [comment]
I have some updates we need.
On the Self-Hosted tab:
- On the Free tier:  remove the "XS and S satellites" and "8 days cache retention" bullet points.
- On the Pro tier:  remove the "From XS to XL satellites", "14 day cache retention", and "Static originating IP address" bullet points. Move the "TLS key rotation", and "Secret provider integrations" bullet points above the "Community support" bullet point. Change the copy in the "Secret provider integrations" bullet point to, "Secrets integrations – e.g. Vault (coming soon)".
- On the Team tier:  remove the "XS to 4XL satellites" and "21 day cache retention" bullet points.
- On the pricing calculator:  Is there any way we can make the right section look less weird? All the space on the bottom-right doesn't look good.
image

On both the Cloud and Self-Hosted tabs:
- On the Enterprise tier:  remove the "Self-hosted satellites (coming soon)" bullet point. Move the "24/7 support" bullet point above the "Secrets integrations" bullet point.

On the Dedicated tab:
- Change the copy that is directly under the Enterprise heading from "Contact us if you are interested in our Enterprise plan." to "Single-tenant SaaS, fully managed by Earthly in your AWS account." Remove the existing "Single-tenant SaaS, fully managed by Earthly in your AWS account" div.

**Comment by thtmnisamnstr** [comment]
One more change. We need to change the copy on the Dedicated tab, from "Dedicated" to "BYOC" (Bring Your Own Cloud). It might also be good to add a heading under the tabs, above the Enterprise box with the copy "Bring Your Own Cloud".

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65cc8b844e60eb896aa09309--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65ccfa997769f200a20d1297--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65cd328ce16f9126ce065a66--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle I made some updates but need a few more from you.
1. I moved the Monthly/Annual toggle to the top of the pricing section, but we don't love it. Can you guys help figure out a better place for it? Also, can you make sure it works correctly too (I think it does, but forgot to check).
2. For the Self-Hosted and BYOC tabs, can you hide the Compute Pricing section entirely?

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65cf982549c7e60d9c2fd0f7--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65cf9d96a1f7ff02c1e8a995--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65d2e50d36f61ed35ef0f7d4--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65d5aef24739fc6b6c86f455--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65d62d1e4739fcd91686f97d--ephemeral-narwhal-3ac3b2.netlify.app/pricing

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
