### PR TITLE
cleaned up satellite sizes and support in the tier boxes

### PR DESCRIPTION
**Pull request by thtmnisamnstr**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64b5b2989e23c6007ab3e43f--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
@vladaionescu Can you review these changes to the Pricing page, https://64b5b2989e23c6007ab3e43f--ephemeral-narwhal-3ac3b2.netlify.app/pricing? I removed satellite size and community support redundancies across the tiers as per Nacho's notes in Slack.

**Comment by vladaionescu** [comment]
I would keep this the way it was, just so the first tier doesn't look so bare-bones. Unless anyone has strong opinions.

**Comment by thtmnisamnstr** [comment]
I don't. I'll delete this PR/branch.

**Pull request closed without merging**
