### PR TITLE
Solution page: Faster builds

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://651ed33ea8dbbc0466438ace--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://652f00c86676860971e145f1--ephemeral-narwhal-3ac3b2.netlify.app/faster-builds

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle Vlad has written 2 blog posts that should publish in the next few weeks, and I'd like to feature those 2 posts directly below the hero and above the Why Earthly section.
image

Work with Shreya, but maybe something like a 2-column version of this from the About Earthly page.
image

The blog posts haven't been published yet, so we don't have URLs or hero images. You can use [https://earthly.dev/blog/the-world-deserves-better-builds/](https://earthly.dev/blog/the-world-deserves-better-builds/) and [https://earthly.dev/blog/earthly-cloud-free-tier-launch/](https://earthly.dev/blog/earthly-cloud-free-tier-launch/) as stand-ins until we do.

Can you also add this to the /solutions page? Below the Earthly + GitHub Actions section.
image

I don't think we have an icon for speed. Could you work with Shreya to see if you can come up with one?

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65322d7467637972b31e212b--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
This looks good. The blog posts are published now.

Let's make this one the 1st link, https://earthly.dev/blog/what-makes-earthly-fast/, and this one the 2nd link, https://earthly.dev/blog/the-roi-of-fast/.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://6536d9db0db8ef1d3e8c642d--ephemeral-narwhal-3ac3b2.netlify.app/faster-builds

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
