### PR TITLE
Pricing toggle design tweaks

### PR DESCRIPTION
**Pull request by avinder-red-crackle**
This PR addresses the design [changes](https://github.com/earthly/website/pull/434#issuecomment-1522150964) requested in earlier pricing toggle PR.

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle The color on the text that begins with "Note:" under the Pricing header is still not the color that Miron specified here https://github.com/earthly/website/pull/434#issuecomment-1522150964. Can you update that?

**Comment by thtmnisamnstr** [comment]
Preview URL: https://645243803152b869e9f0b2ea--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
@mirho I think the pricing page updates you had are implemented. Any further fixes before I merge this one?

**Comment by mirho** [comment]
@thtmnisamnstr it looks good now, you can merge it

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
