### PR TITLE
About Earthly

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by avinder-red-crackle** [comment]
Preview URL: https://65277b6b4c5a0c6d9ec60efa--ephemeral-narwhal-3ac3b2.netlify.app/about-earthly

**Comment by thtmnisamnstr** [comment]
Preview URL: https://652f04e9069c140e444dafb3--ephemeral-narwhal-3ac3b2.netlify.app/about-earthly

**Comment by thtmnisamnstr** [comment]
@avinder-red-crackle On the /about-earthly page, in the timeline, the Feb, 2023 entry should have 2 links instead of one. Work with Shreya, but maybe something like a 2-column version of this.
image

Can you also add it to the bottom navigation on website and blog, under FAQ and above Newsroom.

**Comment by avinder-red-crackle** [comment]
Is this what we are looking for?<br/>
Screenshot 2023-10-18 at 8 59 27 PM

**Comment by thtmnisamnstr** [comment]
Yes. One pointing to https://earthly.dev/blog/new-fundings-at-earthly/ and the other pointing to https://earthly.dev/blog/launching-earthly-ci/.

**Comment by thtmnisamnstr** [comment]
Preview URL: https://653140b84e3bd71e4f82f226--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://653177072b5f8c09fd7870ab--ephemeral-narwhal-3ac3b2.netlify.app/about-earthly

**Comment by thtmnisamnstr** [comment]
Preview URL: https://65318c3346a0ce2340536996--ephemeral-narwhal-3ac3b2.netlify.app/about-earthly

**Review by thtmnisamnstr — APPROVED** [review]

**Pull request merged**
