### PR TITLE
Animation

### PR DESCRIPTION
**Pull request by avinder-red-crackle**

### CODE REVIEW

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64a6d3ca0991213b1ddfa770--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by avinder-red-crackle** [comment]
Preview URL: https://64a81261d6e71006891ac88f--ephemeral-narwhal-3ac3b2.netlify.app

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64ad08a51360c1510a10d11f--ephemeral-narwhal-3ac3b2.netlify.app

**Review by vladaionescu — APPROVED** [review]

**Comment by thtmnisamnstr** [comment]
Preview URL: https://64ad8339f6fb42141b645c52--ephemeral-narwhal-3ac3b2.netlify.app

**Pull request merged**
